services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ragchat-openai-local:latest
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_HOST=${PINECONE_HOST}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MOMENTO_API_KEY=${MOMENTO_API_KEY}
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
